/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person.glb --transform --shadow --types
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "coucou" | "wait" | "walk";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    head: THREE.Mesh;
    armL: THREE.SkinnedMesh;
    armR: THREE.SkinnedMesh;
    body: THREE.SkinnedMesh;
    footL: THREE.SkinnedMesh;
    footR: THREE.SkinnedMesh;
    legL: THREE.SkinnedMesh;
    legR: THREE.SkinnedMesh;
    bassin: THREE.Bone;
    IKtete: THREE.Bone;
    coude_bras_L: THREE.Bone;
    IKpied_L: THREE.Bone;
    IKmain_L: THREE.Bone;
    genou_jambe_L: THREE.Bone;
    coude_bras_R: THREE.Bone;
    IKmain_R: THREE.Bone;
    IKpied_R: THREE.Bone;
    genou_jambe_R: THREE.Bone;
  };
  materials: {
    body: THREE.MeshStandardMaterial;
    armL: THREE.MeshStandardMaterial;
    armR: THREE.MeshStandardMaterial;
    footL: THREE.MeshStandardMaterial;
    footR: THREE.MeshStandardMaterial;
    legL: THREE.MeshStandardMaterial;
    legR: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

interface PersonModelProps extends React.ComponentPropsWithoutRef<"group"> {
  isWalking?: boolean;
  coucouTrigger?: number;
}

export function PersonModel({
  isWalking = false,
  coucouTrigger = 0,
  ...props
}: Readonly<PersonModelProps>) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/person-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  const prevCoucouTrigger = useRef(0);

  useEffect(() => {
    if (isWalking) {
      actions.wait?.fadeOut(0.2);
      actions.walk?.reset().fadeIn(0.2).play();
    } else {
      actions.walk?.fadeOut(0.2);
      actions.wait?.reset().fadeIn(0.2).play();
    }
  }, [isWalking, actions]);

  useEffect(() => {
    if (coucouTrigger > prevCoucouTrigger.current) {
      prevCoucouTrigger.current = coucouTrigger;
      const coucou = actions.coucou;
      if (coucou) {
        coucou
          .reset()
          .fadeIn(0.1)
          .setLoop(THREE.LoopOnce, 1).clampWhenFinished = true;
        coucou.play();
      }
    }
  }, [coucouTrigger, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.bassin} />
          <primitive object={nodes.IKtete} />
          <primitive object={nodes.coude_bras_L} />
          <primitive object={nodes.IKpied_L} />
          <primitive object={nodes.IKmain_L} />
          <primitive object={nodes.genou_jambe_L} />
          <primitive object={nodes.coude_bras_R} />
          <primitive object={nodes.IKmain_R} />
          <primitive object={nodes.IKpied_R} />
          <primitive object={nodes.genou_jambe_R} />
        </group>
        <skinnedMesh
          name="armL"
          geometry={nodes.armL.geometry}
          material={nodes.armL.material}
          skeleton={nodes.armL.skeleton}
          castShadow
        />
        <skinnedMesh
          name="armR"
          geometry={nodes.armR.geometry}
          material={nodes.armR.material}
          skeleton={nodes.armR.skeleton}
          castShadow
        />
        <skinnedMesh
          name="body"
          geometry={nodes.body.geometry}
          material={nodes.body.material}
          skeleton={nodes.body.skeleton}
          castShadow
        />
        <skinnedMesh
          name="footL"
          geometry={nodes.footL.geometry}
          material={nodes.footL.material}
          skeleton={nodes.footL.skeleton}
          castShadow
        />
        <skinnedMesh
          name="footR"
          geometry={nodes.footR.geometry}
          material={nodes.footR.material}
          skeleton={nodes.footR.skeleton}
          castShadow
        />
        <skinnedMesh
          name="legL"
          geometry={nodes.legL.geometry}
          material={nodes.legL.material}
          skeleton={nodes.legL.skeleton}
          castShadow
        />
        <skinnedMesh
          name="legR"
          geometry={nodes.legR.geometry}
          material={nodes.legR.material}
          skeleton={nodes.legR.skeleton}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/person-transformed.glb");
